version: "3.8"

services:
   app:
       image: myorg/myapp
       ports: 
       - 8080:8080
       environment:
              spring.datasource.url: jdbc:mysql://db:3306/student
              spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
              spring.datasource.username: root
              spring.datasource.password: vibha18ravi
              
       depends_on: 
            - db
       networks:
            - default
   db:
       image: mysql
       environment:
               DATABASE_HOST: docker-mysql
               DATABASE_PORT: 3306
               MYSQL_ROOT_PASSWORD: vibha18ravi
               MYSQL_DATABASE: student
               
       networks:
        - default